# application-dev.yml
spring:
  config:
    activate:
      on-profile: dev

      # Redis
  redis.host=prod-redis: 127.0.0.1
  redis.port: 6379
      
  datasource:
    url: jdbc:h2:file:./data/bankingdb
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
logging:
  level:
    com.bank.application: DEBUG